# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\"@\n\x0b\x43\x61lcRequest\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x0b\n\x03op1\x18\x02 \x01(\x01\x12\n\n\x02op\x18\x03 \x01(\t\x12\x0b\n\x03op2\x18\x04 \x01(\x01\"F\n\x0c\x43\x61lcResponse\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\x01\x12\r\n\x05\x65rror\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCREQUEST']._serialized_start=14
  _globals['_CALCREQUEST']._serialized_end=78
  _globals['_CALCRESPONSE']._serialized_start=80
  _globals['_CALCRESPONSE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
